/**:
  ros__parameters:
    joints_map:
      knee_orientation : "><"
      pantograph_leg : false
      odom_scaler: 1.0
      max_linear_velocity_x : 0.25
      max_linear_velocity_y : 0.25
      max_angular_velocity_z : .3
      com_x_translation : 0.0
      swing_height : 0.25
      stance_depth : 0.0
      stance_duration : 0.3
      nominal_height : 0.4

/quadruped_controller_node:
  ros__parameters:
    gait:
      knee_orientation: "><"
      pantograph_leg: false
      odom_scaler: 1.0
      max_linear_velocity_x: 0.25
      max_linear_velocity_y: 0.25
      max_angular_velocity_z: 0.3
      com_x_translation: 0.0
      swing_height: 0.25
      stance_depth: 0.0
      stance_duration: 0.3
      nominal_height: 0.4

/state_estimation_node:
  ros__parameters:
    gait:
      knee_orientation: "><"
      pantograph_leg: false
      odom_scaler: 1.0
      max_linear_velocity_x: 0.25
      max_linear_velocity_y: 0.25
      max_angular_velocity_z: 0.3
      com_x_translation: 0.0
      swing_height: 0.25
      stance_depth: 0.0
      stance_duration: 0.3
      nominal_height: 0.4
